export const SET_USER = "SET_USER";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_LOADING_USER = "SET_LOADING_USER";

// UI
export const SET_LOADING_UI = "SET_LOADING_UI";
export const STOP_LOADING_UI = "STOP_LOADING_UI";